name: i18n Update Servers
# This Workflow will periodically go in:
# 1. Update extras.xliff with any new servers names Mullvad may have added
# 2. File a pr with the changes to extras.xliff

on:
  schedule:
    - cron: "0 7 * * 1" # Every Monday at 7:00 UTC
  workflow_dispatch:

permissions:
  pull-requests: write
  contents: write

jobs:
  main:
    name: Update server name strings
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          submodules: "true"
          persist-credentials: false
      - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
        with:
          python-version: "3.10"
          cache: "pip"
      - run: pip install -r requirements.txt
      - name: Update server name strings
        run: |
          scripts/ci/update_server_names.py
      - uses: peter-evans/create-pull-request@c5a7806660adbe173f04e3e038b0ccdcd758773c # v6
        id: cpr
        with:
          # This may not be github, cuz gh actions cannot self approve
          author: GitHub <noreply@github.com>
          committer: GitHub <noreply@github.com>
          commit-message: "[Bot] Add new server name strings"
          branch: i18n_server_names_automation
          delete-branch: true
          title: "[Bot] Add new server name strings"
          token: ${{ secrets.WIKI_TOKEN }}
