name: UpdateStrings
on:
  workflow_dispatch:
  schedule:
    - cron: '0 7 * * 1-5' # Run Mon-Fri at 7AM UTC
jobs:
  fetch:
    runs-on: ubuntu-20.04
    steps:
      - name: Clone main code repository
        uses: actions/checkout@v2
      - name: Checkout submodules
        shell: bash
        run: |
          auth_header="$(git config --local --get http.https://github.com/.extraheader)"
          git submodule sync --recursive
          git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
      - name: Checkout mozilla-vpn-client-l10n Git
        run: |
          cd i18n/
          git fetch
          default_branch=$(git symbolic-ref refs/remotes/origin/HEAD | sed 's@^refs/remotes/origin/@@')
          git checkout "origin/$default_branch" --force
      - uses: peter-evans/create-pull-request@v3
        with:
          commit-message: "Extract new strings and update all locales"
          branch: l10n_automation
          delete-branch: true
          title: "Extract new strings"
