name: Publish docs in the Wiki
on:
  push:
    branches:
      - main

jobs:
  sync-wiki:
    runs-on: ubuntu-20.04
    steps:
      - name: Clone Code Repo
        uses: actions/checkout@v2
        with:
          path: 'vpn'
          repository: ''
      
      - name: Check if Docs were Changed
        uses: dorny/paths-filter@v2
        id: changes
        with:
          working-directory: 'vpn'
          filters: |
            docs:
              - 'docs/**'
      - name: Clone Wiki Repo
        if: steps.changes.outputs.docs == 'true'
        shell: bash
        run: |
          git clone https://${{secrets.TOKEN}}:@github.com/strseb/mozilla-vpn-client.wiki.git wiki
      - name: Update Contents
        if: steps.changes.outputs.docs == 'true'
        shell: bash
        run: |
          cd wiki
          find . -name "*.md" -type f -delete
          cd ..
          cp -rf vpn/docs wiki/
      - if: steps.changes.outputs.docs == 'true'
        run: |
          cd wiki 
          git config user.name github-actions
          git config user.email ${{ secrets.TOKEN_USER }}
          git config user.password ${{secrets.TOKEN}}
          git add .
          git commit -m "Push ${{ github.sha }} docs changes"
          git push
          